service: default
runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: jinja2
    version: latest
  - name: webapp2
    version: latest

handlers:
  - url: /js
    static_dir: js
    mime_type: "text/javascript"

  - url: /.*
    script: main.APP
    secure: always
